// Code generated by MockGen. DO NOT EDIT.
// Source: item.go

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockItemRepositoryInterface is a mock of ItemRepositoryInterface interface.
type MockItemRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockItemRepositoryInterfaceMockRecorder
}

// MockItemRepositoryInterfaceMockRecorder is the mock recorder for MockItemRepositoryInterface.
type MockItemRepositoryInterfaceMockRecorder struct {
	mock *MockItemRepositoryInterface
}

// NewMockItemRepositoryInterface creates a new mock instance.
func NewMockItemRepositoryInterface(ctrl *gomock.Controller) *MockItemRepositoryInterface {
	mock := &MockItemRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockItemRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemRepositoryInterface) EXPECT() *MockItemRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockItemRepositoryInterface) AddLink(longLink string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", longLink)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockItemRepositoryInterfaceMockRecorder) AddLink(longLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockItemRepositoryInterface)(nil).AddLink), longLink)
}

// SearchLongLink mocks base method.
func (m *MockItemRepositoryInterface) SearchLongLink(shortLink string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLongLink", shortLink)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLongLink indicates an expected call of SearchLongLink.
func (mr *MockItemRepositoryInterfaceMockRecorder) SearchLongLink(shortLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLongLink", reflect.TypeOf((*MockItemRepositoryInterface)(nil).SearchLongLink), shortLink)
}
